# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  policy.csv: |
    p, role:admin, applications, get, */*, allow
    p, role:admin, applications, sync, */*, allow
    p, role:admin, applications, update, */*, allow
    p, role:admin, applications, action/*, */*, allow
    p, role:admin, projects, get, *, allow
    p, role:admin, repositories, get, *, allow
    g, admin, role:admin
    g, admin:login, role:admin
  policy.default: role:readonly
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2026-05-02T23:06:32Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "1777780011637503006"
  uid: 4efc9239-ece6-45d8-b4c0-56b1fffe3b52
