apiVersion: v1
kind: Secret
metadata:
  name: gitlab-jcloud-argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com/UDdeployTemplate/jcloud_argocd.git
  username: oauth2
  password: <GITLAB_TOKEN_glpat-AX5RogqdL5rX-7nG4ae_lmM6MQpvOjEKdTpseXZidQ8.01.170vaoq63>
