version: "3.8"

services:
  springapp:
    image: jcloudcode/jcloud-springboot-app:1              #agunu2025/mss-mongodb-app:1
    container_name: app
    restart: always
    environment:
      MONGO_DB_HOSTNAME: mongo
      MONGO_DB_USERNAME: devdb
      MONGO_DB_PASSWORD: devdb123
    ports:
      - "8075:8080"
    depends_on:
      - mongo
    networks:
      - mss-network

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: devdb
      MONGO_INITDB_ROOT_PASSWORD: devdb123
    volumes:
      - mongodbbkp:/data/db
    networks:
      - mss-network

volumes:
  mongodbbkp:
    external: true

networks:
  mss-network:
    external: true
