apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://jcloudcodes-public-vault-e0a9d77c.e1f8f4d8.z1.hashicorp.cloud:8200"
      path: "kv/jcloudcodes/java-web-app"
      version: "v2"
      namespace: "admin"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets
          key: token
