apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
  namespace: {{ .Values.global.namespaceOverride }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dockerhub-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "{{ `{{ .DOCKER_USERNAME }}` }}",
                "password": "{{ `{{ .DOCKER_PASSWORD }}` }}",
                "auth": "{{ `{{ printf "%s:%s" .DOCKER_USERNAME .DOCKER_PASSWORD | b64enc }}` }}"
              }
            }
          }
  data:
    - secretKey: DOCKER_USERNAME
      remoteRef:
        key: jcloudcodes/java-web-app
        property: DOCKER_USERNAME
    - secretKey: DOCKER_PASSWORD
      remoteRef:
        key: jcloudcodes/java-web-app
        property: DOCKER_PASSWORD
