apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-secret
  namespace: {{ .Values.global.namespaceOverride }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vault.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.vault.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: MONGO_DB_USERNAME
      remoteRef:
        key: {{ .Values.vault.remoteRefs.mongoUsername.key }}
        property: {{ .Values.vault.remoteRefs.mongoUsername.property }}
    - secretKey: MONGO_DB_PASSWORD
      remoteRef:
        key: {{ .Values.vault.remoteRefs.mongoPassword.key }}
        property: {{ .Values.vault.remoteRefs.mongoPassword.property }}
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: {{ .Values.vault.remoteRefs.mongoRootUsername.key }}
        property: {{ .Values.vault.remoteRefs.mongoRootUsername.property }}
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.vault.remoteRefs.mongoRootPassword.key }}
        property: {{ .Values.vault.remoteRefs.mongoRootPassword.property }}
