apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mss.fullname" . }}
  namespace: {{ .Values.global.namespaceOverride }}
spec:
  ingressClassName: {{ .Values.springapp.ingress.className }}
  rules:
    - host: {{ .Values.springapp.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mss.fullname" . }}
                port:
                  number: {{ .Values.springapp.service.port }}
